// client/recognizer.js — RECOGNITION + WS LOGIC ONLY. No DOM, no styling, no UI.
// Owner: Arav. Aarya's UI imports createRecognizer() and renders from the callbacks.
// Do not add HTML/CSS here. Do not edit this file from the UI side.
//
//   const rec = createRecognizer({
//     video,                                  // <video> element the UI owns (we attach the camera)
//     bridgeUrl: "ws://localhost:8787/signal",
//     on: {
//       ready(){}, frame(landmarks){},        // landmarks = 21 {x,y,z} (UI draws the overlay)
//       reading(token, conf){},               // live read-out, every frame
//       sign(token, conf, latencyMs){},       // a sign COMMITTED (verbatim path spoke it)
//       ambiguous(top3){},                    // conf 0.55–0.85 -> UI shows choices -> rec.confirm(label)
//       learned(label, count){},              // enrollment / correction stored (chip + counter)
//       spoken(text){},                       // the agent's spoken sentence (YOU caption)
//       caption(text){},                      // hearing party reply (THEM caption)
//       bridge(connected){},                  // bridge ws up/down
//       error(msg){},
//     },
//   });
//   await rec.start();
//   rec.teachSign("WATER");  rec.confirm("APPOINTMENT");  rec.conductIntent("APPOINTMENT, T,H,U,R,S,D,A,Y");
//   rec.getProfile(); rec.getLexicon(); rec.addLexiconTerm("Zoloft");

import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs";

const HOLD_VEL = 0.03; // below this avg landmark velocity => "held" (raised from 0.018: tolerate natural hand tremor so commits aren't 1s+)
const SHAPE_EPS = 0.025; // max handshape change (fingerSpread delta) to still count as "held". A hand translating slowly toward the next sign (movement epenthesis) has low velocity but a CHANGING handshape — this separates "arrived + holding" from "moving to the next sign". See ASL_DOMAIN.md §segmentation.
const HOLD_FRAMES = 2; // consecutive held frames before commit (~66ms — fire the moment a confident sign is shown)
const ACCEPT = 0.7,
  ASK = 0.45; // confidence gates (loosened so natural signing variation commits fast, not after 4s)
const TAU = 1.2; // distance scale for confidence (raised from 0.55: typical sign distances now map to high confidence)
const COOLDOWN = 700; // ms between same-token emissions (lowered for a more live/continuous feel)
const PAUSE_MS = 5000; // long auto-commit fallback — the FAST path is Send/Space (instant, batches all signs into one sentence)
const MAX_WORDS = 8; // hard cap — commit even without a pause (prevents never-commit on fluent signing)
const MAX_SENTENCE_MS = 6000; // hard cap — commit after this long even if signs keep coming
const CAP_FRAMES = 5; // frames captured per enrollment
const MOTION_VEL = 0.04; // above this avg landmark velocity => dynamic sign candidate
const MOTION_MIN_MS = 240;
const MOTION_SETTLE_MS = 260;
const MOTION_FRAME_GAP = 180;
const MOTION_MAX_FRAMES = 4;
const MOTION_COOLDOWN = 2800;
const MOTION_TIMEOUT_MS = 8000; // VLM round-trip is ~2-3s (non-reasoning VL); 2.2s aborted every real call -> "motion reader unavailable"
const MOTION_MIN_CONF = 0.55;

const WASM =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const PHRASE = {
  HELLO: "Hi there.",
  APPOINTMENT: "Hi, I'd like to book an appointment.",
  THURSDAY: "Thursday works for me.",
  "THANK-YOU": "Thank you so much.",
  YES: "Yes, that works.",
  NO: "No, thank you.",
  CANCEL: "I'd like to cancel that.",
  WAIT: "One moment, please.",
  REPEAT: "Could you repeat that?",
  WATER: "water",
};

export function createRecognizer({
  video,
  bridgeUrl = "ws://localhost:8787/signal",
  vlmUrl = "http://localhost:8788/recognize-omni",
  dynamicRecognition = true,
  dynamicVocab = ["THANK-YOU", "YES", "NO", "HELLO", "WAIT", "REPEAT"],
  on = {},
} = {}) {
  const emit = (name, ...a) => {
    try {
      on[name]?.(...a);
    } catch (e) {}
  };

  let landmarker = null,
    running = false,
    lastVideoTime = -1;
  let recentVecs = [],
    heldCount = 0,
    heldStartT = 0,
    lastEmit = { token: null, t: 0 },
    gateShown = 0,
    prevSpread = null; // last frame's handshape signature (for the stability gate)
  let enroll = null;
  let profile = loadJSON("signal_profile", {}, true); // {label: [Float32Array,...]}
  const lexicon = new Set(loadJSON("signal_lexicon", [], false));
  let bridge = null;

  // ---------- persistence ----------
  function loadJSON(key, fallback, typed) {
    try {
      const o = JSON.parse(localStorage.getItem(key) || "null");
      if (o == null) return fallback;
      if (typed) {
        const out = {};
        for (const k in o) out[k] = o[k].map((a) => Float32Array.from(a));
        return out;
      }
      return o;
    } catch {
      return fallback;
    }
  }
  function saveProfile() {
    const o = {};
    for (const k in profile) o[k] = profile[k].map((a) => Array.from(a));
    localStorage.setItem("signal_profile", JSON.stringify(o));
  }
  function saveLexicon() {
    localStorage.setItem("signal_lexicon", JSON.stringify([...lexicon]));
  }
  // Optional BASE LIBRARY: if the user hasn't taught any signs yet, load a bundled
  // default_profile.json sitting next to recognizer.js (same {label:[[63 floats]...]} shape
  // exportProfile() produces). Never clobbers a user's own taught signs; they augment it.
  async function seedFromDefault() {
    if (Object.keys(profile).length) return false;
    try {
      const res = await fetch(
        new URL("./default_profile.json", import.meta.url),
      );
      if (!res.ok) return false;
      const o = await res.json();
      for (const k in o) profile[k] = o[k].map((a) => Float32Array.from(a));
      saveProfile();
      return Object.keys(profile).length > 0;
    } catch {
      return false;
    }
  }

  // ---------- landmark math ----------
  function normalize(lm) {
    const wrist = lm[0],
      mid = lm[9];
    const scale =
      Math.hypot(
        mid.x - wrist.x,
        mid.y - wrist.y,
        (mid.z || 0) - (wrist.z || 0),
      ) || 1e-6;
    const v = new Float32Array(63);
    for (let i = 0; i < 21; i++) {
      v[i * 3] = (lm[i].x - wrist.x) / scale;
      v[i * 3 + 1] = (lm[i].y - wrist.y) / scale;
      v[i * 3 + 2] = ((lm[i].z || 0) - (wrist.z || 0)) / scale;
    }
    return v;
  }
  // handshape signature: sum of fingertip→MCP distances, scale-normalized by hand
  // size so the value is comparable regardless of distance to camera. Used by the
  // hold gate — a STABLE spread means the handshape stopped forming (arrived), a
  // CHANGING spread means the hand is still articulating / moving to the next sign.
  const TIPS = [4, 8, 12, 16, 20],
    MCPS = [2, 5, 9, 13, 17];
  function fingerSpread(lm) {
    const wrist = lm[0],
      mid = lm[9];
    const scale =
      Math.hypot(mid.x - wrist.x, mid.y - wrist.y, (mid.z || 0) - (wrist.z || 0)) || 1e-6;
    let s = 0;
    for (let i = 0; i < 5; i++) {
      const a = lm[TIPS[i]],
        b = lm[MCPS[i]];
      s += Math.hypot(a.x - b.x, a.y - b.y, (a.z || 0) - (b.z || 0)) / scale;
    }
    return s;
  }
  function dist(a, b) {
    let s = 0;
    for (let i = 0; i < 63; i++) {
      const d = a[i] - b[i];
      s += d * d;
    }
    return Math.sqrt(s);
  }
  function velocity(a, b) {
    return !a || !b ? 1 : dist(a, b) / Math.sqrt(63);
  }
  function avgRecent(n = 3) {
    const k = Math.min(n, recentVecs.length);
    if (!k) return null;
    const out = new Float32Array(63);
    for (let i = recentVecs.length - k; i < recentVecs.length; i++)
      for (let j = 0; j < 63; j++) out[j] += recentVecs[i][j];
    for (let j = 0; j < 63; j++) out[j] /= k;
    return out;
  }
  function classify(v) {
    let best = null,
      bestD = Infinity;
    for (const [label, protos] of Object.entries(profile))
      for (const p of protos) {
        const d = dist(v, p);
        if (d < bestD) {
          bestD = d;
          best = label;
        }
      }
    if (best === null) return { token: null, conf: 0 };
    return { token: best, conf: Math.max(0, Math.min(1, 1 - bestD / TAU)) };
  }
  function topK(v, k = 3) {
    const arr = [];
    for (const [label, protos] of Object.entries(profile)) {
      let b = Infinity;
      for (const p of protos) b = Math.min(b, dist(v, p));
      arr.push([label, b]);
    }
    arr.sort((a, b) => a[1] - b[1]);
    return arr.slice(0, k).map((x) => x[0]);
  }

  // ---------- bridge (WS to the bot) ----------
  function connectBridge() {
    try {
      bridge = new WebSocket(bridgeUrl);
      bridge.onopen = () => emit("bridge", true);
      bridge.onclose = () => {
        emit("bridge", false);
        if (running) setTimeout(connectBridge, 2000);
      };
      bridge.onmessage = (e) => {
        const m = JSON.parse(e.data);
        if (m.type === "caption") emit("caption", m.text);
        else if (m.type === "spoken") emit("spoken", m.text);
      };
    } catch (e) {
      emit("error", "bridge: " + e.message);
    }
  }
  const wsSend = (obj) => {
    if (bridge && bridge.readyState === 1) {
      bridge.send(JSON.stringify(obj));
      return true;
    }
    return false; // caller can keep the payload + retry instead of silently dropping it
  };

  // ---------- motion signs: landmark burst -> VLM -> same sentence buffer ----------
  let motion = {
    active: false,
    busy: false,
    frames: [],
    startedAt: 0,
    lastMoveAt: 0,
    lastFrameAt: 0,
    cooldownUntil: 0,
    suppressUntil: 0,
  };
  function captureFrame() {
    const vw = video.videoWidth || 960;
    const vh = video.videoHeight || 720;
    if (!vw || !vh) return null;
    const maxW = 512;
    const scale = Math.min(1, maxW / vw);
    const canvas = document.createElement("canvas");
    canvas.width = Math.round(vw * scale);
    canvas.height = Math.round(vh * scale);
    const ctx = canvas.getContext("2d", { alpha: false });
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/jpeg", 0.72);
  }
  function addMotionFrame(now) {
    if (now - motion.lastFrameAt < MOTION_FRAME_GAP) return;
    const frame = captureFrame();
    if (!frame) return;
    motion.frames.push(frame);
    if (motion.frames.length > MOTION_MAX_FRAMES) motion.frames.shift();
    motion.lastFrameAt = now;
  }
  async function postMotionFrames(frames) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), MOTION_TIMEOUT_MS);
    try {
      const res = await fetch(vlmUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ frames, vocab: dynamicVocab }),
        signal: controller.signal,
      });
      if (!res.ok) throw new Error(`VLM ${res.status}`);
      return await res.json();
    } finally {
      clearTimeout(timer);
    }
  }
  async function classifyMotion(frames) {
    if (motion.busy || frames.length < 2) return;
    motion.busy = true;
    const t0 = performance.now();
    emit("motion", "reading", { frames: frames.length });
    try {
      const result = await postMotionFrames(frames);
      const token = String(result.sign || "UNKNOWN").toUpperCase();
      const conf = Number(result.confidence ?? 0);
      const latency = Math.round(performance.now() - t0);
      if (
        !dynamicVocab.includes(token) ||
        token === "UNKNOWN" ||
        conf < MOTION_MIN_CONF
      ) {
        emit("motion", "unclear", { ...result, latencyMs: latency });
        return;
      }
      heldCount = 0;
      lastSign = null;
      bufferSign(token, conf, latency);
      emit("motion", "recognized", { ...result, latencyMs: latency });
    } catch (err) {
      emit("motion", "error", err);
    } finally {
      motion.busy = false;
      motion.cooldownUntil = performance.now() + MOTION_COOLDOWN;
    }
  }
  function trackMotion(vel, now) {
    if (
      !dynamicRecognition ||
      enroll ||
      now < motion.cooldownUntil ||
      motion.busy
    ) {
      return now < motion.suppressUntil;
    }
    const moving = vel > MOTION_VEL;
    if (moving) {
      if (!motion.active) {
        motion.active = true;
        motion.frames = [];
        motion.startedAt = now;
        motion.lastFrameAt = 0;
        emit("motion", "capturing", {});
      }
      motion.lastMoveAt = now;
      motion.suppressUntil = now + MOTION_SETTLE_MS + 120;
      heldCount = 0;
      lastSign = null;
      addMotionFrame(now);
      return true;
    }
    if (motion.active) {
      addMotionFrame(now);
      if (now - motion.lastMoveAt >= MOTION_SETTLE_MS) {
        const frames = motion.frames.slice();
        const duration = now - motion.startedAt;
        motion.active = false;
        motion.frames = [];
        motion.suppressUntil = now + 180;
        const probe = avgRecent(3);
        const staticRead = probe ? classify(probe) : { token: null, conf: 0 };
        if (
          staticRead.token &&
          staticRead.conf >= ACCEPT &&
          !dynamicVocab.includes(staticRead.token)
        ) {
          motion.suppressUntil = 0;
          return false;
        }
        if (duration >= MOTION_MIN_MS && frames.length >= 2) {
          void classifyMotion(frames);
        }
      }
      return true;
    }
    return now < motion.suppressUntil;
  }

  // ---------- sentence buffering: accumulate signs -> pause -> Nemotron forms a sentence ----------
  let sentBuf = [],
    lastSign = null,
    pauseTimer = null,
    sentenceStartT = 0;
  function bufferSign(token, conf, ms) {
    // Suppress the SAME held sign repeating frame-to-frame. A DELIBERATE re-raise of the same
    // sign still fires, because handleRecognize resets lastSign whenever the hand moves between signs.
    if (token === lastSign) return;
    lastSign = token;
    if (!sentBuf.length) sentenceStartT = performance.now(); // start the sentence clock
    sentBuf.push(token);
    emit("sign", token, conf, ms); // per-word — UI shows it accumulating
    emit("word", token, [...sentBuf]);
    clearTimeout(pauseTimer);
    // Hard caps so a fluent signer (a new sign every <PAUSE_MS) still commits — never hangs.
    if (
      sentBuf.length >= MAX_WORDS ||
      performance.now() - sentenceStartT >= MAX_SENTENCE_MS
    ) {
      commitSentence();
      return;
    }
    pauseTimer = setTimeout(commitSentence, PAUSE_MS); // pause -> form the sentence
  }
  function commitSentence() {
    if (!running) return; // never fire after stop()
    if (!sentBuf.length) return;
    clearTimeout(pauseTimer);
    const intent = sentBuf.join(", ");
    emit("sentence", intent); // UI: "forming…"
    if (!wsSend({ type: "sign", token: intent, mode: "conduct" })) {
      // Bridge mid-reconnect — KEEP the words + retry; never silently drop the sentence.
      pauseTimer = setTimeout(commitSentence, 800);
      return;
    }
    sentBuf = [];
    lastSign = null;
    sentenceStartT = 0;
  }

  // ---------- recognition ----------
  function handleRecognize(v, vel, now, shapeStable = true) {
    // a true HOLD = low velocity AND handshape stopped changing. Velocity alone
    // false-commits during movement epenthesis (hand drifting slowly to the next
    // sign while the handshape is still forming). See ASL_DOMAIN.md §segmentation.
    const stable = vel < HOLD_VEL && shapeStable;
    if (stable) {
      if (heldCount === 0) heldStartT = now;
      heldCount++;
    } else {
      heldCount = 0;
      lastSign = null; // hand moved between signs — a deliberate repeat (e.g. YES YES) may fire again
    }

    const probe = avgRecent(3) || v;
    const { token, conf } = classify(probe);
    emit("reading", token, conf);

    if (heldCount >= HOLD_FRAMES && token) {
      if (conf >= ACCEPT) {
        heldCount = 0;
        bufferSign(token, conf, Math.round(now - heldStartT)); // accumulate -> sentence (dedupe inside)
      } else if (conf >= ASK && now - gateShown > 2000) {
        gateShown = now;
        enroll && (enroll._probe = probe);
        emit("ambiguous", topK(probe, 3));
        pendingProbe = probe;
      }
    }
  }

  let pendingProbe = null;
  function handleEnroll(v, vel) {
    if (vel < HOLD_VEL && enroll.frames.length < CAP_FRAMES) {
      enroll.frames.push(v);
      if (enroll.frames.length === CAP_FRAMES) {
        const proto = new Float32Array(63);
        for (const f of enroll.frames)
          for (let j = 0; j < 63; j++) proto[j] += f[j];
        for (let j = 0; j < 63; j++) proto[j] /= enroll.frames.length;
        (profile[enroll.label] ||= []).push(proto);
        saveProfile();
        const label = enroll.label;
        enroll = null;
        emit("learned", label, Object.keys(profile).length);
      }
    }
  }

  function loop() {
    if (!running) return;
    const now = performance.now();
    if (landmarker && video.currentTime !== lastVideoTime) {
      lastVideoTime = video.currentTime;
      const res = landmarker.detectForVideo(video, now);
      const lm = res.landmarks && res.landmarks[0];
      emit("frame", lm || null);
      if (lm) {
        const v = normalize(lm);
        const vel = velocity(v, recentVecs[recentVecs.length - 1]);
        recentVecs.push(v);
        if (recentVecs.length > 8) recentVecs.shift();
        // handshape stability: how much the spread changed since last frame
        const spread = fingerSpread(lm);
        const shapeStable = prevSpread === null || Math.abs(spread - prevSpread) < SHAPE_EPS;
        prevSpread = spread;
        if (enroll) handleEnroll(v, vel);
        else if (!trackMotion(vel, now)) handleRecognize(v, vel, now, shapeStable);
      } else {
        motion.active = false;
        heldCount = 0;
        prevSpread = null; // hand left frame — reset so re-entry isn't a false "stable"
      }
    }
    requestAnimationFrame(loop);
  }

  // ---------- public API ----------
  return {
    async start() {
      try {
        const fs = await FilesetResolver.forVisionTasks(WASM);
        landmarker = await HandLandmarker.createFromOptions(fs, {
          baseOptions: { modelAssetPath: MODEL, delegate: "GPU" },
          runningMode: "VIDEO",
          numHands: 1,
        });
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: 960, height: 720 },
        });
        video.srcObject = stream;
        video.muted = true; // required for autoplay
        await new Promise((r) => (video.onloadeddata = r));
        // IMPORTANT: the <video> must NOT be display:none (a hidden video won't
        // advance currentTime, so no frames reach MediaPipe). Use width:1px/opacity:0
        // if you need it invisible. Force playback explicitly to be safe:
        try {
          await video.play();
        } catch (e) {}
        running = true;
        connectBridge();
        await seedFromDefault(); // load the base sign library if the user has taught none yet
        emit("ready");
        loop();
      } catch (err) {
        emit("error", err.message);
        throw err;
      }
    },
    // begin enrolling a new sign: hold steady, captures CAP_FRAMES -> emits "learned"
    teachSign(label) {
      enroll = {
        label: String(label).toUpperCase().replace(/\s+/g, "-"),
        frames: [],
      };
    },
    // store a correction for an ambiguous read (the user tapped the right label)
    confirm(label) {
      if (pendingProbe) {
        (profile[label] ||= []).push(pendingProbe);
        saveProfile();
        const text = PHRASE[label] || label.toLowerCase();
        wsSend({ type: "sign", token: label, text, mode: "verbatim" });
        emit("learned", label, Object.keys(profile).length);
        pendingProbe = null;
      }
    },
    // the AGENT path: raw signed intent -> Nemotron -> sentence (arrives via on.spoken)
    conductIntent(intent) {
      wsSend({ type: "sign", token: intent, mode: "conduct" });
    },
    // manual fallback/debug trigger; normal motion signs are detected automatically.
    async readMotionSign() {
      const frames = [];
      for (let i = 0; i < MOTION_MAX_FRAMES; i++) {
        const frame = captureFrame();
        if (frame) frames.push(frame);
        if (i < MOTION_MAX_FRAMES - 1) {
          await new Promise((resolve) => setTimeout(resolve, MOTION_FRAME_GAP));
        }
      }
      await classifyMotion(frames);
    },
    // force the buffered signs to commit NOW (e.g. user taps "send") instead of waiting for the pause
    commitNow() {
      commitSentence();
    },
    // the signs accumulated so far this sentence (UI can render them live)
    getBuffer() {
      return [...sentBuf];
    },
    getProfile() {
      return Object.fromEntries(
        Object.entries(profile).map(([k, v]) => [k, v.length]),
      );
    },
    // dump the taught vocabulary — paste into client/default_profile.json to ship a base library
    exportProfile() {
      const o = {};
      for (const k in profile) o[k] = profile[k].map((a) => Array.from(a));
      return o;
    },
    // load a base library of signs; merges by default (user's taught signs win unless replace:true)
    importProfile(o, { replace = false } = {}) {
      for (const k in o) {
        const protos = o[k].map((a) => Float32Array.from(a));
        if (replace || !profile[k]) profile[k] = protos;
        else profile[k].push(...protos);
      }
      saveProfile();
      return Object.keys(profile).length;
    },
    getLexicon() {
      return [...lexicon];
    },
    addLexiconTerm(t) {
      lexicon.add(t);
      saveLexicon();
    },
    stop() {
      running = false;
      clearTimeout(pauseTimer); // kill any pending commit so it can't fire post-stop
      pauseTimer = null;
      sentBuf = [];
      lastSign = null;
      sentenceStartT = 0;
      motion.active = false;
      motion.frames = [];
      try {
        bridge && bridge.close();
      } catch {}
    },
  };
}
