// client/recognizer.js — RECOGNITION + WS LOGIC ONLY. No DOM, no styling, no UI.
// Owner: Arav. Aarya's UI imports createRecognizer() and renders from the callbacks.
// Do not add HTML/CSS here. Do not edit this file from the UI side.
//
//   const rec = createRecognizer({
//     video,                                  // <video> element the UI owns (we attach the camera)
//     bridgeUrl: "ws://localhost:8787/signal",
//     on: {
//       ready(){}, frame(landmarks){},        // landmarks = 21 {x,y,z} (UI draws the overlay)
//       reading(token, conf){},               // live read-out, every frame
//       sign(token, conf, latencyMs){},       // a sign COMMITTED (verbatim path spoke it)
//       ambiguous(top3){},                    // conf 0.55–0.85 -> UI shows choices -> rec.confirm(label)
//       learned(label, count){},              // enrollment / correction stored (chip + counter)
//       spoken(text){},                       // the agent's spoken sentence (YOU caption)
//       caption(text){},                      // hearing party reply (THEM caption)
//       bridge(connected){},                  // bridge ws up/down
//       error(msg){},
//     },
//   });
//   await rec.start();
//   rec.teachSign("WATER");  rec.confirm("APPOINTMENT");  rec.conductIntent("APPOINTMENT, T,H,U,R,S,D,A,Y");
//   rec.getProfile(); rec.getLexicon(); rec.addLexiconTerm("Zoloft");

import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs";

const HOLD_VEL = 0.03; // below this avg landmark velocity => "held" (raised from 0.018: tolerate natural hand tremor so commits aren't 1s+)
const HOLD_FRAMES = 2; // consecutive held frames before commit (~66ms — fire the moment a confident sign is shown)
const ACCEPT = 0.7,
  ASK = 0.45; // confidence gates (loosened so natural signing variation commits fast, not after 4s)
const TAU = 1.2; // distance scale for confidence (raised from 0.55: typical sign distances now map to high confidence)
const COOLDOWN = 700; // ms between same-token emissions (lowered for a more live/continuous feel)
const PAUSE_MS = 1500; // ms with no new sign before buffered signs become ONE spoken sentence
const MAX_WORDS = 8; // hard cap — commit even without a pause (prevents never-commit on fluent signing)
const MAX_SENTENCE_MS = 6000; // hard cap — commit after this long even if signs keep coming
const CAP_FRAMES = 5; // frames captured per enrollment

const WASM =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const PHRASE = {
  HELLO: "Hi there.",
  APPOINTMENT: "Hi, I'd like to book an appointment.",
  THURSDAY: "Thursday works for me.",
  "THANK-YOU": "Thank you so much.",
  YES: "Yes, that works.",
  NO: "No, thank you.",
  CANCEL: "I'd like to cancel that.",
  WAIT: "One moment, please.",
  REPEAT: "Could you repeat that?",
  WATER: "water",
};

export function createRecognizer({
  video,
  bridgeUrl = "ws://localhost:8787/signal",
  on = {},
} = {}) {
  const emit = (name, ...a) => {
    try {
      on[name]?.(...a);
    } catch (e) {}
  };

  let landmarker = null,
    running = false,
    lastVideoTime = -1;
  let recentVecs = [],
    heldCount = 0,
    heldStartT = 0,
    lastEmit = { token: null, t: 0 },
    gateShown = 0;
  let enroll = null;
  let profile = loadJSON("signal_profile", {}, true); // {label: [Float32Array,...]}
  const lexicon = new Set(loadJSON("signal_lexicon", [], false));
  let bridge = null;

  // ---------- persistence ----------
  function loadJSON(key, fallback, typed) {
    try {
      const o = JSON.parse(localStorage.getItem(key) || "null");
      if (o == null) return fallback;
      if (typed) {
        const out = {};
        for (const k in o) out[k] = o[k].map((a) => Float32Array.from(a));
        return out;
      }
      return o;
    } catch {
      return fallback;
    }
  }
  function saveProfile() {
    const o = {};
    for (const k in profile) o[k] = profile[k].map((a) => Array.from(a));
    localStorage.setItem("signal_profile", JSON.stringify(o));
  }
  function saveLexicon() {
    localStorage.setItem("signal_lexicon", JSON.stringify([...lexicon]));
  }
  // Optional BASE LIBRARY: if the user hasn't taught any signs yet, load a bundled
  // default_profile.json sitting next to recognizer.js (same {label:[[63 floats]...]} shape
  // exportProfile() produces). Never clobbers a user's own taught signs; they augment it.
  async function seedFromDefault() {
    if (Object.keys(profile).length) return false;
    try {
      const res = await fetch(
        new URL("./default_profile.json", import.meta.url),
      );
      if (!res.ok) return false;
      const o = await res.json();
      for (const k in o) profile[k] = o[k].map((a) => Float32Array.from(a));
      saveProfile();
      return Object.keys(profile).length > 0;
    } catch {
      return false;
    }
  }

  // ---------- landmark math ----------
  function normalize(lm) {
    const wrist = lm[0],
      mid = lm[9];
    const scale =
      Math.hypot(
        mid.x - wrist.x,
        mid.y - wrist.y,
        (mid.z || 0) - (wrist.z || 0),
      ) || 1e-6;
    const v = new Float32Array(63);
    for (let i = 0; i < 21; i++) {
      v[i * 3] = (lm[i].x - wrist.x) / scale;
      v[i * 3 + 1] = (lm[i].y - wrist.y) / scale;
      v[i * 3 + 2] = ((lm[i].z || 0) - (wrist.z || 0)) / scale;
    }
    return v;
  }
  function dist(a, b) {
    let s = 0;
    for (let i = 0; i < 63; i++) {
      const d = a[i] - b[i];
      s += d * d;
    }
    return Math.sqrt(s);
  }
  function velocity(a, b) {
    return !a || !b ? 1 : dist(a, b) / Math.sqrt(63);
  }
  function avgRecent(n = 3) {
    const k = Math.min(n, recentVecs.length);
    if (!k) return null;
    const out = new Float32Array(63);
    for (let i = recentVecs.length - k; i < recentVecs.length; i++)
      for (let j = 0; j < 63; j++) out[j] += recentVecs[i][j];
    for (let j = 0; j < 63; j++) out[j] /= k;
    return out;
  }
  function classify(v) {
    let best = null,
      bestD = Infinity;
    for (const [label, protos] of Object.entries(profile))
      for (const p of protos) {
        const d = dist(v, p);
        if (d < bestD) {
          bestD = d;
          best = label;
        }
      }
    if (best === null) return { token: null, conf: 0 };
    return { token: best, conf: Math.max(0, Math.min(1, 1 - bestD / TAU)) };
  }
  function topK(v, k = 3) {
    const arr = [];
    for (const [label, protos] of Object.entries(profile)) {
      let b = Infinity;
      for (const p of protos) b = Math.min(b, dist(v, p));
      arr.push([label, b]);
    }
    arr.sort((a, b) => a[1] - b[1]);
    return arr.slice(0, k).map((x) => x[0]);
  }

  // ---------- bridge (WS to the bot) ----------
  function connectBridge() {
    try {
      bridge = new WebSocket(bridgeUrl);
      bridge.onopen = () => emit("bridge", true);
      bridge.onclose = () => {
        emit("bridge", false);
        if (running) setTimeout(connectBridge, 2000);
      };
      bridge.onmessage = (e) => {
        const m = JSON.parse(e.data);
        if (m.type === "caption") emit("caption", m.text);
        else if (m.type === "spoken") emit("spoken", m.text);
      };
    } catch (e) {
      emit("error", "bridge: " + e.message);
    }
  }
  const wsSend = (obj) => {
    if (bridge && bridge.readyState === 1) {
      bridge.send(JSON.stringify(obj));
      return true;
    }
    return false; // caller can keep the payload + retry instead of silently dropping it
  };

  // ---------- sentence buffering: accumulate signs -> pause -> Nemotron forms a sentence ----------
  let sentBuf = [],
    lastSign = null,
    pauseTimer = null,
    sentenceStartT = 0;
  function bufferSign(token, conf, ms) {
    // Suppress the SAME held sign repeating frame-to-frame. A DELIBERATE re-raise of the same
    // sign still fires, because handleRecognize resets lastSign whenever the hand moves between signs.
    if (token === lastSign) return;
    lastSign = token;
    if (!sentBuf.length) sentenceStartT = performance.now(); // start the sentence clock
    sentBuf.push(token);
    emit("sign", token, conf, ms); // per-word — UI shows it accumulating
    emit("word", token, [...sentBuf]);
    clearTimeout(pauseTimer);
    // Hard caps so a fluent signer (a new sign every <PAUSE_MS) still commits — never hangs.
    if (
      sentBuf.length >= MAX_WORDS ||
      performance.now() - sentenceStartT >= MAX_SENTENCE_MS
    ) {
      commitSentence();
      return;
    }
    pauseTimer = setTimeout(commitSentence, PAUSE_MS); // pause -> form the sentence
  }
  function commitSentence() {
    if (!running) return; // never fire after stop()
    if (!sentBuf.length) return;
    clearTimeout(pauseTimer);
    const intent = sentBuf.join(", ");
    emit("sentence", intent); // UI: "forming…"
    if (!wsSend({ type: "sign", token: intent, mode: "conduct" })) {
      // Bridge mid-reconnect — KEEP the words + retry; never silently drop the sentence.
      pauseTimer = setTimeout(commitSentence, 800);
      return;
    }
    sentBuf = [];
    lastSign = null;
    sentenceStartT = 0;
  }

  // ---------- recognition ----------
  function handleRecognize(v, vel, now) {
    const stable = vel < HOLD_VEL;
    if (stable) {
      if (heldCount === 0) heldStartT = now;
      heldCount++;
    } else {
      heldCount = 0;
      lastSign = null; // hand moved between signs — a deliberate repeat (e.g. YES YES) may fire again
    }

    const probe = avgRecent(3) || v;
    const { token, conf } = classify(probe);
    emit("reading", token, conf);

    if (heldCount >= HOLD_FRAMES && token) {
      if (conf >= ACCEPT) {
        heldCount = 0;
        bufferSign(token, conf, Math.round(now - heldStartT)); // accumulate -> sentence (dedupe inside)
      } else if (conf >= ASK && now - gateShown > 2000) {
        gateShown = now;
        enroll && (enroll._probe = probe);
        emit("ambiguous", topK(probe, 3));
        pendingProbe = probe;
      }
    }
  }

  let pendingProbe = null;
  function handleEnroll(v, vel) {
    if (vel < HOLD_VEL && enroll.frames.length < CAP_FRAMES) {
      enroll.frames.push(v);
      if (enroll.frames.length === CAP_FRAMES) {
        const proto = new Float32Array(63);
        for (const f of enroll.frames)
          for (let j = 0; j < 63; j++) proto[j] += f[j];
        for (let j = 0; j < 63; j++) proto[j] /= enroll.frames.length;
        (profile[enroll.label] ||= []).push(proto);
        saveProfile();
        const label = enroll.label;
        enroll = null;
        emit("learned", label, Object.keys(profile).length);
      }
    }
  }

  function loop() {
    if (!running) return;
    const now = performance.now();
    if (landmarker && video.currentTime !== lastVideoTime) {
      lastVideoTime = video.currentTime;
      const res = landmarker.detectForVideo(video, now);
      const lm = res.landmarks && res.landmarks[0];
      emit("frame", lm || null);
      if (lm) {
        const v = normalize(lm);
        const vel = velocity(v, recentVecs[recentVecs.length - 1]);
        recentVecs.push(v);
        if (recentVecs.length > 8) recentVecs.shift();
        if (enroll) handleEnroll(v, vel);
        else handleRecognize(v, vel, now);
      } else heldCount = 0;
    }
    requestAnimationFrame(loop);
  }

  // ---------- public API ----------
  return {
    async start() {
      try {
        const fs = await FilesetResolver.forVisionTasks(WASM);
        landmarker = await HandLandmarker.createFromOptions(fs, {
          baseOptions: { modelAssetPath: MODEL, delegate: "GPU" },
          runningMode: "VIDEO",
          numHands: 1,
        });
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: 960, height: 720 },
        });
        video.srcObject = stream;
        video.muted = true; // required for autoplay
        await new Promise((r) => (video.onloadeddata = r));
        // IMPORTANT: the <video> must NOT be display:none (a hidden video won't
        // advance currentTime, so no frames reach MediaPipe). Use width:1px/opacity:0
        // if you need it invisible. Force playback explicitly to be safe:
        try {
          await video.play();
        } catch (e) {}
        running = true;
        connectBridge();
        await seedFromDefault(); // load the base sign library if the user has taught none yet
        emit("ready");
        loop();
      } catch (err) {
        emit("error", err.message);
        throw err;
      }
    },
    // begin enrolling a new sign: hold steady, captures CAP_FRAMES -> emits "learned"
    teachSign(label) {
      enroll = {
        label: String(label).toUpperCase().replace(/\s+/g, "-"),
        frames: [],
      };
    },
    // store a correction for an ambiguous read (the user tapped the right label)
    confirm(label) {
      if (pendingProbe) {
        (profile[label] ||= []).push(pendingProbe);
        saveProfile();
        const text = PHRASE[label] || label.toLowerCase();
        wsSend({ type: "sign", token: label, text, mode: "verbatim" });
        emit("learned", label, Object.keys(profile).length);
        pendingProbe = null;
      }
    },
    // the AGENT path: raw signed intent -> Nemotron -> sentence (arrives via on.spoken)
    conductIntent(intent) {
      wsSend({ type: "sign", token: intent, mode: "conduct" });
    },
    // force the buffered signs to commit NOW (e.g. user taps "send") instead of waiting for the pause
    commitNow() {
      commitSentence();
    },
    // the signs accumulated so far this sentence (UI can render them live)
    getBuffer() {
      return [...sentBuf];
    },
    getProfile() {
      return Object.fromEntries(
        Object.entries(profile).map(([k, v]) => [k, v.length]),
      );
    },
    // dump the taught vocabulary — paste into client/default_profile.json to ship a base library
    exportProfile() {
      const o = {};
      for (const k in profile) o[k] = profile[k].map((a) => Array.from(a));
      return o;
    },
    // load a base library of signs; merges by default (user's taught signs win unless replace:true)
    importProfile(o, { replace = false } = {}) {
      for (const k in o) {
        const protos = o[k].map((a) => Float32Array.from(a));
        if (replace || !profile[k]) profile[k] = protos;
        else profile[k].push(...protos);
      }
      saveProfile();
      return Object.keys(profile).length;
    },
    getLexicon() {
      return [...lexicon];
    },
    addLexiconTerm(t) {
      lexicon.add(t);
      saveLexicon();
    },
    stop() {
      running = false;
      clearTimeout(pauseTimer); // kill any pending commit so it can't fire post-stop
      pauseTimer = null;
      sentBuf = [];
      lastSign = null;
      sentenceStartT = 0;
      try {
        bridge && bridge.close();
      } catch {}
    },
  };
}
