// client/recognizer.js — RECOGNITION + WS LOGIC ONLY. No DOM, no styling, no UI.
// Owner: Arav. Aarya's UI imports createRecognizer() and renders from the callbacks.
// Do not add HTML/CSS here. Do not edit this file from the UI side.
//
//   const rec = createRecognizer({
//     video,                                  // <video> element the UI owns (we attach the camera)
//     bridgeUrl: "ws://localhost:8787/signal",
//     on: {
//       ready(){}, frame(landmarks){},        // landmarks = 21 {x,y,z} (UI draws the overlay)
//       reading(token, conf){},               // live read-out, every frame
//       sign(token, conf, latencyMs){},       // a sign COMMITTED (verbatim path spoke it)
//       ambiguous(top3){},                    // conf 0.55–0.85 -> UI shows choices -> rec.confirm(label)
//       learned(label, count){},              // enrollment / correction stored (chip + counter)
//       spoken(text){},                       // the agent's spoken sentence (YOU caption)
//       caption(text){},                      // hearing party reply (THEM caption)
//       bridge(connected){},                  // bridge ws up/down
//       error(msg){},
//     },
//   });
//   await rec.start();
//   rec.teachSign("WATER");  rec.confirm("APPOINTMENT");  rec.conductIntent("APPOINTMENT, T,H,U,R,S,D,A,Y");
//   rec.getProfile(); rec.getLexicon(); rec.addLexiconTerm("Zoloft");

import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs";

const HOLD_VEL = 0.03; // below this avg landmark velocity => "held" (raised from 0.018: tolerate natural hand tremor so commits aren't 1s+)
const HOLD_FRAMES = 2; // consecutive held frames before commit (~66ms — fire the moment a confident sign is shown)
const ACCEPT = 0.85,
  ASK = 0.55; // confidence gates
const TAU = 0.55; // distance scale for confidence
const COOLDOWN = 1200; // ms between same-token emissions
const CAP_FRAMES = 5; // frames captured per enrollment

const WASM =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const PHRASE = {
  HELLO: "Hi there.",
  APPOINTMENT: "Hi, I'd like to book an appointment.",
  THURSDAY: "Thursday works for me.",
  "THANK-YOU": "Thank you so much.",
  YES: "Yes, that works.",
  NO: "No, thank you.",
  CANCEL: "I'd like to cancel that.",
  WAIT: "One moment, please.",
  REPEAT: "Could you repeat that?",
  WATER: "water",
};

export function createRecognizer({
  video,
  bridgeUrl = "ws://localhost:8787/signal",
  on = {},
} = {}) {
  const emit = (name, ...a) => {
    try {
      on[name]?.(...a);
    } catch (e) {}
  };

  let landmarker = null,
    running = false,
    lastVideoTime = -1;
  let recentVecs = [],
    heldCount = 0,
    heldStartT = 0,
    lastEmit = { token: null, t: 0 },
    gateShown = 0;
  let enroll = null;
  let profile = loadJSON("signal_profile", {}, true); // {label: [Float32Array,...]}
  const lexicon = new Set(loadJSON("signal_lexicon", [], false));
  let bridge = null;

  // ---------- persistence ----------
  function loadJSON(key, fallback, typed) {
    try {
      const o = JSON.parse(localStorage.getItem(key) || "null");
      if (o == null) return fallback;
      if (typed) {
        const out = {};
        for (const k in o) out[k] = o[k].map((a) => Float32Array.from(a));
        return out;
      }
      return o;
    } catch {
      return fallback;
    }
  }
  function saveProfile() {
    const o = {};
    for (const k in profile) o[k] = profile[k].map((a) => Array.from(a));
    localStorage.setItem("signal_profile", JSON.stringify(o));
  }
  function saveLexicon() {
    localStorage.setItem("signal_lexicon", JSON.stringify([...lexicon]));
  }

  // ---------- landmark math ----------
  function normalize(lm) {
    const wrist = lm[0],
      mid = lm[9];
    const scale =
      Math.hypot(
        mid.x - wrist.x,
        mid.y - wrist.y,
        (mid.z || 0) - (wrist.z || 0),
      ) || 1e-6;
    const v = new Float32Array(63);
    for (let i = 0; i < 21; i++) {
      v[i * 3] = (lm[i].x - wrist.x) / scale;
      v[i * 3 + 1] = (lm[i].y - wrist.y) / scale;
      v[i * 3 + 2] = ((lm[i].z || 0) - (wrist.z || 0)) / scale;
    }
    return v;
  }
  function dist(a, b) {
    let s = 0;
    for (let i = 0; i < 63; i++) {
      const d = a[i] - b[i];
      s += d * d;
    }
    return Math.sqrt(s);
  }
  function velocity(a, b) {
    return !a || !b ? 1 : dist(a, b) / Math.sqrt(63);
  }
  function avgRecent(n = 3) {
    const k = Math.min(n, recentVecs.length);
    if (!k) return null;
    const out = new Float32Array(63);
    for (let i = recentVecs.length - k; i < recentVecs.length; i++)
      for (let j = 0; j < 63; j++) out[j] += recentVecs[i][j];
    for (let j = 0; j < 63; j++) out[j] /= k;
    return out;
  }
  function classify(v) {
    let best = null,
      bestD = Infinity;
    for (const [label, protos] of Object.entries(profile))
      for (const p of protos) {
        const d = dist(v, p);
        if (d < bestD) {
          bestD = d;
          best = label;
        }
      }
    if (best === null) return { token: null, conf: 0 };
    return { token: best, conf: Math.max(0, Math.min(1, 1 - bestD / TAU)) };
  }
  function topK(v, k = 3) {
    const arr = [];
    for (const [label, protos] of Object.entries(profile)) {
      let b = Infinity;
      for (const p of protos) b = Math.min(b, dist(v, p));
      arr.push([label, b]);
    }
    arr.sort((a, b) => a[1] - b[1]);
    return arr.slice(0, k).map((x) => x[0]);
  }

  // ---------- bridge (WS to the bot) ----------
  function connectBridge() {
    try {
      bridge = new WebSocket(bridgeUrl);
      bridge.onopen = () => emit("bridge", true);
      bridge.onclose = () => {
        emit("bridge", false);
        if (running) setTimeout(connectBridge, 2000);
      };
      bridge.onmessage = (e) => {
        const m = JSON.parse(e.data);
        if (m.type === "caption") emit("caption", m.text);
        else if (m.type === "spoken") emit("spoken", m.text);
      };
    } catch (e) {
      emit("error", "bridge: " + e.message);
    }
  }
  const wsSend = (obj) =>
    bridge && bridge.readyState === 1 && bridge.send(JSON.stringify(obj));

  // ---------- recognition ----------
  function handleRecognize(v, vel, now) {
    const stable = vel < HOLD_VEL;
    if (stable) {
      if (heldCount === 0) heldStartT = now;
      heldCount++;
    } else heldCount = 0;

    const probe = avgRecent(3) || v;
    const { token, conf } = classify(probe);
    emit("reading", token, conf);

    if (heldCount >= HOLD_FRAMES && token) {
      if (conf >= ACCEPT) {
        if (!(lastEmit.token === token && now - lastEmit.t < COOLDOWN)) {
          lastEmit = { token, t: now };
          heldCount = 0;
          const text = PHRASE[token] || token.toLowerCase();
          wsSend({ type: "sign", token, text, mode: "verbatim" });
          emit("sign", token, conf, Math.round(now - heldStartT));
        }
      } else if (conf >= ASK && now - gateShown > 2000) {
        gateShown = now;
        enroll && (enroll._probe = probe);
        emit("ambiguous", topK(probe, 3));
        pendingProbe = probe;
      }
    }
  }

  let pendingProbe = null;
  function handleEnroll(v, vel) {
    if (vel < HOLD_VEL && enroll.frames.length < CAP_FRAMES) {
      enroll.frames.push(v);
      if (enroll.frames.length === CAP_FRAMES) {
        const proto = new Float32Array(63);
        for (const f of enroll.frames)
          for (let j = 0; j < 63; j++) proto[j] += f[j];
        for (let j = 0; j < 63; j++) proto[j] /= enroll.frames.length;
        (profile[enroll.label] ||= []).push(proto);
        saveProfile();
        const label = enroll.label;
        enroll = null;
        emit("learned", label, Object.keys(profile).length);
      }
    }
  }

  function loop() {
    if (!running) return;
    const now = performance.now();
    if (landmarker && video.currentTime !== lastVideoTime) {
      lastVideoTime = video.currentTime;
      const res = landmarker.detectForVideo(video, now);
      const lm = res.landmarks && res.landmarks[0];
      emit("frame", lm || null);
      if (lm) {
        const v = normalize(lm);
        const vel = velocity(v, recentVecs[recentVecs.length - 1]);
        recentVecs.push(v);
        if (recentVecs.length > 8) recentVecs.shift();
        if (enroll) handleEnroll(v, vel);
        else handleRecognize(v, vel, now);
      } else heldCount = 0;
    }
    requestAnimationFrame(loop);
  }

  // ---------- public API ----------
  return {
    async start() {
      try {
        const fs = await FilesetResolver.forVisionTasks(WASM);
        landmarker = await HandLandmarker.createFromOptions(fs, {
          baseOptions: { modelAssetPath: MODEL, delegate: "GPU" },
          runningMode: "VIDEO",
          numHands: 1,
        });
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: 960, height: 720 },
        });
        video.srcObject = stream;
        video.muted = true; // required for autoplay
        await new Promise((r) => (video.onloadeddata = r));
        // IMPORTANT: the <video> must NOT be display:none (a hidden video won't
        // advance currentTime, so no frames reach MediaPipe). Use width:1px/opacity:0
        // if you need it invisible. Force playback explicitly to be safe:
        try {
          await video.play();
        } catch (e) {}
        running = true;
        connectBridge();
        emit("ready");
        loop();
      } catch (err) {
        emit("error", err.message);
        throw err;
      }
    },
    // begin enrolling a new sign: hold steady, captures CAP_FRAMES -> emits "learned"
    teachSign(label) {
      enroll = {
        label: String(label).toUpperCase().replace(/\s+/g, "-"),
        frames: [],
      };
    },
    // store a correction for an ambiguous read (the user tapped the right label)
    confirm(label) {
      if (pendingProbe) {
        (profile[label] ||= []).push(pendingProbe);
        saveProfile();
        const text = PHRASE[label] || label.toLowerCase();
        wsSend({ type: "sign", token: label, text, mode: "verbatim" });
        emit("learned", label, Object.keys(profile).length);
        pendingProbe = null;
      }
    },
    // the AGENT path: raw signed intent -> Nemotron -> sentence (arrives via on.spoken)
    conductIntent(intent) {
      wsSend({ type: "sign", token: intent, mode: "conduct" });
    },
    getProfile() {
      return Object.fromEntries(
        Object.entries(profile).map(([k, v]) => [k, v.length]),
      );
    },
    getLexicon() {
      return [...lexicon];
    },
    addLexiconTerm(t) {
      lexicon.add(t);
      saveLexicon();
    },
    stop() {
      running = false;
      try {
        bridge && bridge.close();
      } catch {}
    },
  };
}
